-- AlterTable
ALTER TABLE "contas" ALTER COLUMN "criadoEm" DROP DEFAULT,
ALTER COLUMN "criadoEm" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "editadoEm" DROP DEFAULT,
ALTER COLUMN "editadoEm" SET DATA TYPE TIMESTAMP(3);
