-- AlterTable
ALTER TABLE "Conta" ALTER COLUMN "criadoEm" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "editadoEm" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "clientes" ALTER COLUMN "criadoEm" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "editadoEm" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "logs" ALTER COLUMN "criadoEm" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "lojista_tokens" ALTER COLUMN "expires_date" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "pagamentos" ALTER COLUMN "dataPagamento" SET DATA TYPE TIMESTAMPTZ(3);
