-- AlterTable
ALTER TABLE "Conta" ALTER COLUMN "criadoEm" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "editadoEm" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "clientes" ALTER COLUMN "criadoEm" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "editadoEm" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "logs" ALTER COLUMN "criadoEm" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "lojistaTokens" ALTER COLUMN "expiresDate" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "criadoEm" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "pagamentos" ALTER COLUMN "dataPagamento" SET DATA TYPE TIMESTAMPTZ(3);
